# This is an example configuration for the performance testing framework.
# This is a YAML file and supports the YAML 1.1 Spec.

# Each setting name in here is case insensitive.

# This is the default settings block
# These are the default settings for each test.  If you do not specify a
# setting in a test, the setting will be grabbed from here.
# You must always have all these settings except "csoar directories" and "seed"
# if you are not using csoar and/or are not using seeds.
# Each of these settings can also be specified on a per test basis including
# versions of CSoar to use!
default:
    - jsoar enabled: TRUE
    - csoar enabled: TRUE
    - csoar directories: [ 'resources/csoar/' ] # can list multiple versions of csoar to use
    - warmup count: 2
    - run count: 2
    - decision cycles: 0 # run until test halts
    - use seed: FALSE
    - seed: 1 # seed is disabled by default, but if a test enables it, it will be this by default
    - csv directory: resources/Test-Results
    - jvm settings: -Xmx512M

#
# Here are some example tests.
#

# For each test you have to specify "test<N>" where <N> can be
# anything so long as the keys are unique!  You will get silent
# errors if the keys are not unique.
test:
    - name: wait-snc
    - path: resources/APT/wait.soar
    - decision cycles: 100

test2:
    - name: wait-snc-no-warmup
    - path: resources/APT/wait.soar
    - decision cycles: 100
    - warmup count: 0
    - csoar enabled: FALSE
